---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - service
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.srvptt2.online
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.srvptt2.online
  resources:
  - agents/finalizers
  verbs:
  - update
- apiGroups:
  - app.srvptt2.online
  resources:
  - agents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.srvptt2.online
  resources:
  - lobbies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.srvptt2.online
  resources:
  - lobbies/finalizers
  verbs:
  - update
- apiGroups:
  - app.srvptt2.online
  resources:
  - lobbies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
