apiVersion: app.srvptt2.online/v1
kind: Agent
metadata:
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent-sample
    app.kubernetes.io/part-of: app-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: app-controller
  name: agent-sample
spec:
  # TODO(user): Add fields here
